---
- hosts: local
  gather_facts: true
  vars:
    ansible_connection: local
    user: "{{ ansible_env.USER }}"
    email: steve.lorimer@gmail.com
    postfix_domain: postfix.lori.com
    postfix_email: "{{ email | regex_replace('^(.*)@.*$', '\\\\1') }}+{{ ansible_hostname }}@{{ email | regex_replace('^.*@(.*)$', '\\\\1') }}"
  sudo: false
  user: "{{ user }}"
  roles:
    - ubuntu-base
    - ubuntu-dev
    - ubuntu-steve-env

