---
- hosts: local
  gather_facts: true
  vars:
    ansible_connection: local
    email: steve@vivcourt.com
    postfix_domain: vivcourt.com
    postfix_email: {{ email | regex_replace('(.*)@(.*)', '\\1') }}+{{ user }}-{{ ansible_env.HOST}}-{{postfix_domain}}@{{ email | regex_replace('(.*)@(.*)', '\\2') }}
  sudo: false
  user: "{{ ansible_env.USER }}"
  roles:
    - ubuntu-base
    - ubuntu-dev
    - ubuntu-vivcourt
    - ubuntu-steve-env

