---
- hosts: local
  gather_facts: true
  vars:
    ansible_connection: local
    email: steve.lorimer@gmail.com
    myhostname: theloris.org
    notify_email: "{{ email }}"
    # notify_email: "{{ email | regex_replace('^(.*)@.*$', '\\\\1') }}+{{ ansible_hostname }}@{{ email | regex_replace('^.*@(.*)$', '\\\\1') }}"
  sudo: false
  user: "{{ user }}"
  roles:
    - ubuntu-base
    - ubuntu-dev
    - ubuntu-ide
    - ubuntu-steve-env
    - ubuntu-raid-client

