---
- name: Install required packages
  apt: pkg={{item}} state=installed
  with_items:
    - compizconfig-settings-manager
    - eclipse-cdt
    - eclipse-cdt-valgrind
    - eclipse-cdt-perf
    - eclipse-cdt-profiling-framework
    - eclipse-egit
    # - eclipse-cdt-launch-remote
    # - eclipse-cdt-profiling-framework-remote
    # - eclipse-cdt-valgrind-remote
    # - eclipse-rcp
    # - eclipse-rse
  sudo: true

- name: Download dotfiles
  git: repo=https://github.com/stevelorimer/dotfiles.git dest={{ ansible_env.HOME }}/.dotfiles

- name: Install dotfiles
  shell: cd {{ ansible_env.HOME }}/.dotfiles; ./install_local

- name: Disable unity search
  shell: wget -q -O - https://fixubuntu.com/fixubuntu.sh | bash

- name: Disable show desktop in alt-tab
  command: gsettings set org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/ disable-show-desktop true

- name: Enable integrated menus (show menus in windows title bar)
  command: gsettings set com.canonical.Unity integrated-menus true

- name: Set default nautilus folder view to list-view
  command: gsettings set org.gnome.nautilus.preferences default-folder-viewer "'list-view'"

- name: Set default nautilus list-view zoom to smallest
  command: gsettings set org.gnome.nautilus.list-view default-zoom-level "smallest"

- name: Set default nautilus icon-view zoom to small
  command: gsettings set org.gnome.nautilus.icon-view default-zoom-level "small"

- name: Set gnome-terminal scrollback_lines to 10000
  command: gconftool-2 -t int --set /apps/gnome-terminal/profiles/Default/scrollback_lines 10000

- name: Disable overlay scrollbars
  command: gsettings set com.canonical.desktop.interface scrollbar-mode normal
