---
- name: Install required packages
  apt: pkg={{item}} state=installed
  with_items:
    - libgoogle-perftools-dev
    - libboost1.55-all-dev
    - libzmq3-dev
  sudo: true

- name: Add ssh key to servers
  shell: ssh-copy-id -i {{ ansible_env.HOME }}/.ssh/id_rsa.pub {{ item }}
  with_items:
    - hoff
    - seagal

- include: include/build.yml
    package=protobuf
    package_url={{ google_proto_buf_src }}
    creates=/usr/lib/libprotobufas.a
    ext=tar.gz
    unpacked_dir={{ google_proto_buf_ver }}

# - include: include/build.yml
#     package=zeromq
#     package_url={{ zeromq_src }}
#     creates=/usr/lib/libzmq.a
#     ext=tar.gz
#     unpacked_dir={{ zeromq_ver }}

- name: Install pyev
  pip: name=pyev version={{ pyev_ver }}
  sudo: true

- name: Add Intel apt key
  apt_key: url={{ item }} state=present
  sudo: true
  with_items:
    - {{ intel_public_key }}
    - {{ intel_public_key_2 }}

- name: Download Intel Graphics
  get_url: url={{ intel_graphics_deb }} dest=/tmp/intel-graphics.deb

- name: Install Intel Graphics
  apt: deb=/tmp/intel-graphics.deb
  sudo: true

