---
- name: Install required packages
  apt: pkg={{item}} state=installed
  with_items: required_packages
  sudo: true

- name: Download dotfiles
  git: repo=https://github.com/stevelorimer/dotfiles.git dest={{ ansible_env.HOME }}/.dotfiles

- name: Install dotfiles
  shell: cd {{ ansible_env.HOME }}/.dotfiles && make

- name: Disable unity search
  shell: wget -q -O - https://fixubuntu.com/fixubuntu.sh | bash