---
- name: Install required packages
  apt: pkg={{item}} state=installed
  with_items:
    - compizconfig-settings-manager
    - dconf-editor
    - eclipse-cdt
    - eclipse-cdt-valgrind
    - eclipse-cdt-perf
    - eclipse-cdt-profiling-framework
    - eclipse-egit
    # - eclipse-cdt-launch-remote
    # - eclipse-cdt-profiling-framework-remote
    # - eclipse-cdt-valgrind-remote
    # - eclipse-rcp
    # - eclipse-rse
    - ipython-notebook
  sudo: true
